POST {{host}}/sign-up/
Accept: application/json
Content-Type: application/json

{
  "email": "{{needy_email}}",
  "name": "{{needy_name}}",
  "password": "{{password}}"
}
###

POST {{host}}/sign-up/
Accept: application/json
Content-Type: application/json

{
  "email": "{{helper_email}}",
  "name": "{{helper_name}}",
  "password": "{{password}}"
}
###

###

POST {{host}}/sign-up/
Accept: application/json
Content-Type: application/json

{
  "email": "{{other_user_email}}",
  "name": "{{other_user_name}}",
  "password": "{{password}}"
}
###